version: '2'

services:

    ############################################
    #           Server Configuration           #
    ############################################

    nginx:
        container_name: nginx
        build: docker/nginx
        ports:
            - "80:80"
        links:
            - php
        volumes_from:
            - php
        volumes:
            - ./var/logs/nginx/:/var/log/nginx

    php:
        container_name: php
        build: docker/php
        ports:
            - "9000:9000"
        links:
            - db
            - mailcatcher
        volumes:
            - ./:/var/www/app
            - ./var/logs:/var/www/app/var/logs

    ############################################
    #          Database Configuration          #
    ############################################

    db:
        container_name: db
        image: mariadb
        environment:
            MYSQL_ROOT_PASSWORD: app_1
            MYSQL_DATABASE: app_1
            MYSQL_USER: app_1
            MYSQL_PASSWORD: app_1
        ports:
            - "3306:3306"
        volumes:
            - db:/var/lib/mysql

    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin/phpmyadmin
        ports:
            - "8080:80"
        links:
            - db

    ############################################
    #            Mail Configuration            #
    ############################################

    mailcatcher:
        container_name: mailcatcher
        image: schickling/mailcatcher
        ports:
            - "1080:1080"

    #############################
    #                           #
    # To do                     #
    # _________________________ #
    #                           #
    # Install Elasticsearch     #
    # Install Logstash          #
    #                           #
    #############################

volumes:
    db: ~
